/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "scdax.h"
#include <getopt.h>
#include <time.h>
#include <string.h>     /* for memset() */
#include <stdlib.h>


void DieWithError(char *errorMessage)
{
    perror(errorMessage);
    exit(1);
}

void build_message(int encrypt, char* key, char* address, char* mes, char* ret_buffer)
{
    time_t tiempo = time(0);
    struct tm *tlocal = localtime(&tiempo);
    char output[128];
    strftime(output,128,"%d/%m/%Y %H:%M:%S",tlocal);

    /*if (encrypt == 1) {
    	strcpy(ret_buffer, "CIF\n");
    }else{
    	strcpy(ret_buffer, "DES\n");
    }*/

    strcpy(ret_buffer, "CIF\n");
    printf("%s\n", ret_buffer);
    strcat(ret_buffer, "key: ");
    strcat(ret_buffer, key); //ARREGLAR ESTO
    strcat(ret_buffer, "\n");
    strcat(ret_buffer, "address: ");
    strcat(ret_buffer, address);
    strcat(ret_buffer, "\n");
    strcat(ret_buffer, "time: ");
    strcat(ret_buffer, output);
    strcat(ret_buffer, "\n");
    strcat(ret_buffer, mes);
}

void
scdax_prog_1(char *host, char* longClave, char* dirCifrado)
{
	CLIENT *clnt;
	int  *result_1;
	message  encrypt_msg_1_arg;
	int  *result_2;
	message  decrypt_msg_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SCDAX_PROG, SCDAX_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	encrypt_msg_1_arg.msg = malloc(MSGSIZE * sizeof(char));
	encrypt_msg_1_arg.msg_size = 4;
	encrypt_msg_1_arg.out_msg = malloc(MSGSIZE * sizeof(char));
	//encrypt_msg_1_arg.out_msg = "HEYYY\n";
	//encrypt_msg_1_arg.out_msg = concat(encrypt_msg_1_arg.out_msg, "Agregar");
	build_message(1, longClave, dirCifrado, encrypt_msg_1_arg.msg, encrypt_msg_1_arg.out_msg);
	printf("Hola\n");
	result_1 = encrypt_msg_1(&encrypt_msg_1_arg, clnt);
	printf("Hola1\n");
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	/*result_2 = decrypt_msg_1(&decrypt_msg_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}*/
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char *longClave;
    char *dirCifrado;
    char *nombreArchivoProcesar;

	if (argc < 9 || argc > 11)
        DieWithError("ERROR: Cantidad de argumentos invalidos.\n"
        "   Introduzca: scdax_cli -i <dir_ip> -c <long_clave> -a <dir_cif> -f <archivo_a_procesar> ");


    int option = 0;
    while((option = getopt(argc, argv,"i:c:a:f:")) != -1) 
    {
        switch (option)
        {
            case 'i':
                host = optarg;
                break;
            case 'c':
                longClave = optarg;
                int key;
                if (!(key=atoi(longClave)))
                    DieWithError("ERROR: EL VALOR SEGUIDO DE [-c] DEBE SER UN NUMERO ENTERO");
                if ( (key < 1) || (key > 27) )
                    DieWithError("ERROR: EL VALOR SEGUIDO DE [-c] DEBE ESTAR COMPRENDIDO ENTRE 1 Y 27");
                break;
            case 'a':
                dirCifrado = optarg;     
                if ( (strcmp("derecha",dirCifrado)!=0) || !(strcmp("izquierda",dirCifrado)!=0) )
                    DieWithError("ERROR: EL VALOR SEGUIDO DE [-a] DEBE TOMAR LOS VALORES \"izquierda\" O \"derecha\"");
                break;
            case 'f':
                nombreArchivoProcesar = optarg;
                break;
            case '?':
                DieWithError("ERROR: Argumentos invalidos.\n"
                "   Introduzca: scdax_cli -i <dir_ip> -c <long_clave> -a <dir_cif> -f <archivo_a_procesar> ");
                break;
        }
    }

	scdax_prog_1(host, longClave, dirCifrado);
	exit (0);
}
