/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "scdax.h"

void DieWithError(char *errorMessage)
{
    perror(errorMessage);
    exit(1);
}

int *
encrypt_msg_1_svc(message *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	 result = 1;
	 printf("%s\n", argp->out_msg);

	return &result;
}

int *
decrypt_msg_1_svc(message *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
