/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SCDAX_H_RPCGEN
#define _SCDAX_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define RCVBUFSIZE 32
#define OUTBUFSIZE 160
#define LETTERSIZE 26
#define BACONSIZE 6
#define MSGSIZE 2048

struct message {
	char *msg;
	int msg_size;
	char *out_msg;
};
typedef struct message message;

#define SCDAX_PROG 0x31111112
#define SCDAX_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ENCRYPT_MSG 1
extern  int * encrypt_msg_1(message *, CLIENT *);
extern  int * encrypt_msg_1_svc(message *, struct svc_req *);
#define DECRYPT_MSG 2
extern  int * decrypt_msg_1(message *, CLIENT *);
extern  int * decrypt_msg_1_svc(message *, struct svc_req *);
extern int scdax_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ENCRYPT_MSG 1
extern  int * encrypt_msg_1();
extern  int * encrypt_msg_1_svc();
#define DECRYPT_MSG 2
extern  int * decrypt_msg_1();
extern  int * decrypt_msg_1_svc();
extern int scdax_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_message (XDR *, message*);

#else /* K&R C */
extern bool_t xdr_message ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SCDAX_H_RPCGEN */
